import numpy


r"""
Linear algebra
==============


"""

from pyscf.lib import logger
from openms import __config__

SAFE_EIGH_LINDEP = getattr(__config__, 'linalg_safe_eigh_lindep', 1e-15)
DAVIDSON_LINDEP = getattr(__config__, 'linalg_davidson_lindep', 1e-14)
DSOLVE_LINDEP = getattr(__config__, 'linalg_dsolve_lindep', 1e-13)
MAX_MEMORY = getattr(__config__, 'linalg_davidson_max_memory', 4000)  # 4GB
FOLLOW_STATE = getattr(__config__, 'linalg_davidson_follow_state', False)




def _fill_heff_hermitian(heff, xs, ax, xt, axt, dot):
    nrow = len(axt)
    row1 = len(ax)
    row0 = row1 - nrow
    for ip, i in enumerate(range(row0, row1)):
        for jp, j in enumerate(range(row0, i)):
            heff[i,j] = dot(xt[ip].conj(), axt[jp])
            heff[j,i] = heff[i,j].conj()
        heff[i,i] = dot(xt[ip].conj(), axt[ip]).real

    for i in range(row0):
        axi = numpy.asarray(ax[i])
        for jp, j in enumerate(range(row0, row1)):
            heff[j,i] = dot(xt[jp].conj(), axi)
            heff[i,j] = heff[j,i].conj()
        axi = None
    return heff

def _fill_heff(heff, xs, ax, xt, axt, dot):
    nrow = len(axt)
    row1 = len(ax)
    row0 = row1 - nrow
    for ip, i in enumerate(range(row0, row1)):
        for jp, j in enumerate(range(row0, row1)):
            heff[i,j] = dot(xt[ip].conj(), axt[jp])

    for i in range(row0):
        axi = numpy.asarray(ax[i])
        xi = numpy.asarray(xs[i])
        for jp, j in enumerate(range(row0, row1)):
            heff[i,j] = dot(xi.conj(), axt[jp])
            heff[j,i] = dot(xt[jp].conj(), axi)
        axi = xi = None
    return heff



# subspace eigen solvers
def davidson(
    aop,
    x0,
    precond,
    tol=1e-12,
    max_cycle=50,
    max_space=12,
    lindep=DAVIDSON_LINDEP,
    max_memory=MAX_MEMORY,
    dot=numpy.dot,
    callback=None,
    nroots=1,
    lessio=False,
    pick=None,
    verbose=logger.WARN,
    follow_state=FOLLOW_STATE,
):
    r"""Davidson diagonalization method to solve  a c = e c.
    Ref
    [1] E.R. Davidson, J. Comput. Phys. 17 (1), 87-94 (1975).
    [2] http://people.inf.ethz.ch/arbenz/ewp/Lnotes/chapter11.pdf

    Note: This function has an overhead of memory usage ~4*x0.size*nroots

    Args:
        aop : function(x) => array_like_x
            aop(x) to mimic the matrix vector multiplication :math:`\sum_{j}a_{ij}*x_j`.
            The argument is a 1D array.  The returned value is a 1D array.
        x0 : 1D array or a list of 1D array
            Initial guess.  The initial guess vector(s) are just used as the
            initial subspace bases.  If the subspace is smaller than "nroots",
            eg 10 roots and one initial guess, all eigenvectors are chosen as
            the eigenvectors during the iterations.  The first iteration has
            one eigenvector, the next iteration has two, the third iteration
            has 4, ..., until the subspace size > nroots.
        precond : diagonal elements of the matrix or  function(dx, e, x0) => array_like_dx
            Preconditioner to generate new trial vector.
            The argument dx is a residual vector ``a*x0-e*x0``; e is the current
            eigenvalue; x0 is the current eigenvector.

    Kwargs:
        tol : float
            Convergence tolerance.
        max_cycle : int
            max number of iterations.
        max_space : int
            space size to hold trial vectors.
        lindep : float
            Linear dependency threshold.  The function is terminated when the
            smallest eigenvalue of the metric of the trial vectors is lower
            than this threshold.
        max_memory : int or float
            Allowed memory in MB.
        dot : function(x, y) => scalar
            Inner product
        callback : function(envs_dict) => None
            callback function takes one dict as the argument which is
            generated by the builtin function :func:`locals`, so that the
            callback function can access all local variables in the current
            environment.
        nroots : int
            Number of eigenvalues to be computed.  When nroots > 1, it affects
            the shape of the return value
        lessio : bool
            How to compute a*x0 for current eigenvector x0.  There are two
            ways to compute a*x0.  One is to assemble the existed a*x.  The
            other is to call aop(x0).  The default is the first method which
            needs more IO and less computational cost.  When IO is slow, the
            second method can be considered.
        pick : function(w,v,nroots) => (e[idx], w[:,idx], idx)
            Function to filter eigenvalues and eigenvectors.
        follow_state : bool
            If the solution dramatically changes in two iterations, clean the
            subspace and restart the iteration with the old solution.  It can
            help to improve numerical stability.  Default is False.

    Returns:
        e : float or list of floats
            Eigenvalue.  By default it's one float number.  If :attr:`nroots` > 1, it
            is a list of floats for the lowest :attr:`nroots` eigenvalues.
        c : 1D array or list of 1D arrays
            Eigenvector.  By default it's a 1D array.  If :attr:`nroots` > 1, it
            is a list of arrays for the lowest :attr:`nroots` eigenvectors.

    Examples:

    >>> from openms.solvers import linalg
    >>> a = numpy.random.random((10,10))
    >>> a = a + a.T
    >>> aop = lambda x: numpy.dot(a,x)
    >>> precond = lambda dx, e, x0: dx/(a.diagonal()-e)
    >>> x0 = a[0]
    >>> e, c = linalg.davidson(aop, x0, precond)
    """
    e, x = davidson1(
        lambda xs: [aop(x) for x in xs],
        x0,
        precond,
        tol,
        max_cycle,
        max_space,
        lindep,
        max_memory,
        dot,
        callback,
        nroots,
        lessio,
        pick,
        verbose,
        follow_state,
    )[1:]
    if nroots == 1:
        return e[0], x[0]
    else:
        return e, x


def davidson1(
    aop,
    x0,
    precond,
    tol=1e-12,
    max_cycle=50,
    max_space=12,
    lindep=DAVIDSON_LINDEP,
    max_memory=MAX_MEMORY,
    dot=numpy.dot,
    callback=None,
    nroots=1,
    lessio=False,
    pick=None,
    verbose=logger.WARN,
    follow_state=FOLLOW_STATE,
    tol_residual=None,
    fill_heff=_fill_heff_hermitian,
):
    r"""Davidson diagonalization method to solve  a c = e c.
    Ref:
    [1] E.R. Davidson, J. Comput. Phys. 17 (1), 87-94 (1975).
    [2] http://people.inf.ethz.ch/arbenz/ewp/Lnotes/chapter11.pdf

    Note: This function has an overhead of memory usage ~4*x0.size*nroots

    Args:
        aop : function([x]) => [array_like_x]
            Matrix vector multiplication :math:`y_{ki} = \sum_{j}a_{ij}*x_{jk}`.
        x0 : 1D array or a list of 1D arrays or a function to generate x0 array(s)
            Initial guess.  The initial guess vector(s) are just used as the
            initial subspace bases.  If the subspace is smaller than "nroots",
            eg 10 roots and one initial guess, all eigenvectors are chosen as
            the eigenvectors during the iterations.  The first iteration has
            one eigenvector, the next iteration has two, the third iteration
            has 4, ..., until the subspace size > nroots.
        precond : diagonal elements of the matrix or  function(dx, e, x0) => array_like_dx
            Preconditioner to generate new trial vector.
            The argument dx is a residual vector ``a*x0-e*x0``; e is the current
            eigenvalue; x0 is the current eigenvector.

    Kwargs:
        tol : float
            Convergence tolerance.
        max_cycle : int
            max number of iterations.
        max_space : int
            space size to hold trial vectors.
        lindep : float
            Linear dependency threshold.  The function is terminated when the
            smallest eigenvalue of the metric of the trial vectors is lower
            than this threshold.
        max_memory : int or float
            Allowed memory in MB.
        dot : function(x, y) => scalar
            Inner product
        callback : function(envs_dict) => None
            callback function takes one dict as the argument which is
            generated by the builtin function :func:`locals`, so that the
            callback function can access all local variables in the current
            environment.
        nroots : int
            Number of eigenvalues to be computed.  When nroots > 1, it affects
            the shape of the return value
        lessio : bool
            How to compute a*x0 for current eigenvector x0.  There are two
            ways to compute a*x0.  One is to assemble the existed a*x.  The
            other is to call aop(x0).  The default is the first method which
            needs more IO and less computational cost.  When IO is slow, the
            second method can be considered.
        pick : function(w,v,nroots) => (e[idx], w[:,idx], idx)
            Function to filter eigenvalues and eigenvectors.
        follow_state : bool
            If the solution dramatically changes in two iterations, clean the
            subspace and restart the iteration with the old solution.  It can
            help to improve numerical stability.  Default is False.

    Returns:
        conv : bool
            Converged or not
        e : list of floats
            The lowest :attr:`nroots` eigenvalues.
        c : list of 1D arrays
            The lowest :attr:`nroots` eigenvectors.

    Examples:

    >>> from pyscf import lib
    >>> a = numpy.random.random((10,10))
    >>> a = a + a.T
    >>> aop = lambda xs: [numpy.dot(a,x) for x in xs]
    >>> precond = lambda dx, e, x0: dx/(a.diagonal()-e)
    >>> x0 = a[0]
    >>> e, c = lib.davidson(aop, x0, precond, nroots=2)
    >>> len(e)
    2
    """
    if isinstance(verbose, logger.Logger):
        log = verbose
    else:
        log = logger.Logger(sys.stdout, verbose)

    if tol_residual is None:
        toloose = numpy.sqrt(tol)
    else:
        toloose = tol_residual
    log.debug1("tol %g  toloose %g", tol, toloose)

    if not callable(precond):
        precond = make_diag_precond(precond)

    if callable(x0):  # lazy initialization to reduce memory footprint
        x0 = x0()
    if isinstance(x0, numpy.ndarray) and x0.ndim == 1:
        x0 = [x0]
    # max_cycle = min(max_cycle, x0[0].size)
    max_space = max_space + (nroots - 1) * 4
    # max_space*2 for holding ax and xs, nroots*2 for holding axt and xt
    _incore = max_memory * 1e6 / x0[0].nbytes > max_space * 2 + nroots * 3
    lessio = lessio and not _incore
    log.debug1(
        "max_cycle %d  max_space %d  max_memory %d  incore %s",
        max_cycle,
        max_space,
        max_memory,
        _incore,
    )
    dtype = None
    heff = None
    fresh_start = True
    e = None
    v = None
    conv = numpy.zeros(nroots, dtype=bool)
    emin = None

    for icyc in range(max_cycle):
        if fresh_start:
            if _incore:
                xs = []
                ax = []
            else:
                xs = _Xlist()
                ax = _Xlist()
            space = 0
            # Orthogonalize xt space because the basis of subspace xs must be orthogonal
            # but the eigenvectors x0 might not be strictly orthogonal
            xt = None
            x0len = len(x0)
            xt = _qr(x0, dot, lindep)[0]
            if len(xt) != x0len:
                log.warn("QR decomposition removed %d vectors.", x0len - len(xt))
                if callable(pick):
                    log.warn(
                        "Check to see if `pick` function %s is providing "
                        "linear dependent vectors",
                        pick.__name__,
                    )
                if len(xt) == 0:
                    if icyc == 0:
                        msg = "Initial guess is empty or zero"
                    else:
                        msg = (
                            "No more linearly independent basis were found. "
                            "Unless loosen the lindep tolerance (current value "
                            f"{lindep}), the diagonalization solver is not able "
                            "to find eigenvectors."
                        )
                    raise LinearDependenceError(msg)
            x0 = None
            max_dx_last = 1e9
            if SORT_EIG_BY_SIMILARITY:
                conv = numpy.zeros(nroots, dtype=bool)
        elif len(xt) > 1:
            xt = _qr(xt, dot, lindep)[0]
            xt = xt[:40]  # 40 trial vectors at most

        axt = aop(xt)
        for k, xi in enumerate(xt):
            xs.append(xt[k])
            ax.append(axt[k])
        rnow = len(xt)
        head, space = space, space + rnow

        if dtype is None:
            try:
                dtype = numpy.result_type(axt[0], xt[0])
            except IndexError:
                raise LinearDependenceError(
                    "No linearly independent basis found "
                    "by the diagonalization solver."
                )
        if heff is None:  # Lazy initialize heff to determine the dtype
            heff = numpy.empty((max_space + nroots, max_space + nroots), dtype=dtype)
        else:
            heff = numpy.asarray(heff, dtype=dtype)

        elast = e
        vlast = v
        conv_last = conv

        fill_heff(heff, xs, ax, xt, axt, dot)
        xt = axt = None
        w, v = scipy.linalg.eigh(heff[:space, :space])
        if callable(pick):
            w, v, idx = pick(w, v, nroots, locals())
            if len(w) == 0:
                raise RuntimeError(f"Not enough eigenvalues found by {pick}")

        if SORT_EIG_BY_SIMILARITY:
            e, v = _sort_by_similarity(w, v, nroots, conv, vlast, emin)
        else:
            e = w[:nroots]
            v = v[:, :nroots]
            conv = numpy.zeros(e.size, dtype=bool)
            if not fresh_start:
                elast, conv_last = _sort_elast(elast, conv_last, vlast, v, log)

        if elast is None:
            de = e
        elif elast.size != e.size:
            log.debug(
                "Number of roots different from the previous step (%d,%d)",
                e.size,
                elast.size,
            )
            de = e
        else:
            de = e - elast

        x0 = None
        x0 = _gen_x0(v, xs)
        if lessio:
            ax0 = aop(x0)
        else:
            ax0 = _gen_x0(v, ax)

        dx_norm = numpy.zeros(e.size)
        xt = [None] * nroots
        for k, ek in enumerate(e):
            xt[k] = ax0[k] - ek * x0[k]
            dx_norm[k] = numpy.sqrt(dot(xt[k].conj(), xt[k]).real)
            conv[k] = abs(de[k]) < tol and dx_norm[k] < toloose
            if conv[k] and not conv_last[k]:
                log.debug(
                    "root %d converged  |r|= %4.3g  e= %s  max|de|= %4.3g",
                    k,
                    dx_norm[k],
                    ek,
                    de[k],
                )
        ax0 = None
        max_dx_norm = max(dx_norm)
        ide = numpy.argmax(abs(de))
        if all(conv):
            log.debug(
                "converged %d %d  |r|= %4.3g  e= %s  max|de|= %4.3g",
                icyc,
                space,
                max_dx_norm,
                e,
                de[ide],
            )
            break
        elif (
            follow_state
            and max_dx_norm > 1
            and max_dx_norm / max_dx_last > 3
            and space > nroots + 2
        ):
            log.debug(
                "davidson %d %d  |r|= %4.3g  e= %s  max|de|= %4.3g",
                icyc,
                space,
                max_dx_norm,
                e,
                de[ide],
            )
            log.debug("Large |r| detected, restore to previous x0")
            x0 = _gen_x0(vlast, xs)
            fresh_start = True
            continue

        if SORT_EIG_BY_SIMILARITY:
            if any(conv) and e.dtype == numpy.double:
                emin = min(e)

        # remove subspace linear dependency
        for k, ek in enumerate(e):
            if (not conv[k]) and dx_norm[k] ** 2 > lindep:
                xt[k] = precond(xt[k], e[0], x0[k])
                xt[k] *= dot(xt[k].conj(), xt[k]).real ** -0.5
            elif not conv[k]:
                # Remove linearly dependent vector
                xt[k] = None
                log.debug1("Drop eigenvector %d, norm=%4.3g", k, dx_norm[k])
            else:
                xt[k] = None

        xt, norm_min = _normalize_xt_(xt, xs, lindep, dot)
        log.debug(
            "davidson %d %d  |r|= %4.3g  e= %s  max|de|= %4.3g  lindep= %4.3g",
            icyc,
            space,
            max_dx_norm,
            e,
            de[ide],
            norm_min,
        )
        if len(xt) == 0:
            log.debug(
                "Linear dependency in trial subspace. |r| for each state %s", dx_norm
            )
            conv = dx_norm < toloose
            break

        max_dx_last = max_dx_norm
        fresh_start = space + nroots > max_space

        if callable(callback):
            callback(locals())

    x0 = list(x0)  # nparray -> list

    # Check whether the solver finds enough eigenvectors.
    h_dim = x0[0].size
    if len(x0) < min(h_dim, nroots):
        # Two possible reasons:
        # 1. All the initial guess are the eigenvectors. No more trial vectors
        # can be generated.
        # 2. The initial guess sits in the subspace which is smaller than the
        # required number of roots.
        log.warn(f"Not enough eigenvectors (len(x0)={len(x0)}, nroots={nroots})")

    return numpy.asarray(conv), e, x0


def make_diag_precond(diag, level_shift=1e-3):
    """Generate the preconditioner function with the diagonal function."""

    # For diagonal matrix A, precond (Ax-x*e)/(diag(A)-e) is not able to
    # generate linearly independent basis (see issue 1362). Use level_shift to
    # break the correlation between Ax-x*e and diag(A)-e.
    def precond(dx, e, *args):
        diagd = diag - (e - level_shift)
        diagd[abs(diagd) < 1e-8] = 1e-8
        return dx / diagd

    return precond


def davidson1(
    matvec,
    x0,
    precond,
    tol=1e-12,
    max_cycle=50,
    max_space=12,
    lindep=DAVIDSON_LINDEP,
    max_memory=MAX_MEMORY,
    dot=numpy.dot,
    callback=None,
    nroots=1,
    lessio=False,
    pick=None,
    verbose=logger.WARN,
    follow_state=FOLLOW_STATE,
    tol_residual=None,
    fill_heff=_fill_heff_hermitian,
):
    r"""Davidson diagonalization method to solve  a c = e c.
    Ref:

    """
    pass


def lanczos(
    matvec,
    x0,
    tol=1e-12,
    max_cycle=50,
    max_space=12,
    max_memory=MAX_MEMORY,
    dot=numpy.dot,
    callback=None,
    nroots=1,
    lessio=False,
    pick=None,
    verbose=logger.WARN,
    follow_state=FOLLOW_STATE,
    tol_residual=None,
    fill_heff=_fill_heff_hermitian,
):
    r"""Lanczos diagonalization method to solve  a c = e c.
    Ref:

    """
    pass
