# query EIGEN3_DIR and (deprecated) EIGEN_DIR envvars
if (DEFINED ENV{EIGEN3_DIR})
  set(ENV_EIGEN3_DIR "$ENV{EIGEN3_DIR}")
else()
  set(ENV_EIGEN3_DIR "$ENV{EIGEN_DIR}")
endif()
set(EIGEN3_INCLUDE_DIR "${ENV_EIGEN3_DIR}" CACHE PATH "Eigen3 library directory")

if (MADNESS_LINALG_USE_LAPACKE IN_LIST LAPACK_COMPILE_DEFINITIONS)
  list(APPEND LAPACK_COMPILE_DEFINITIONS TILEDARRAY_EIGEN_USE_LAPACKE)
endif()
